import {
  Megaphone,
  Laugh,
  Clapperboard,
  Mic2,
  Shirt,
  Sparkles,
  UtensilsCrossed,
  MapPin,
  Backpack,
  Coffee,
  Palette,
  Smartphone,
  Sprout,
  Flame,
  Rocket,
  Crown,
  Waves,
  TrendingDown,
  Skull,
  Home,
  Compass,
  Radar,
  Star,
  LayoutGrid,
  Search,
  ArrowLeft,
  Check,
  Plus,
  Share2,
  Lightbulb,
  TrendingUp,
  Clock,
  Hash,
  Network,
  ShoppingBag,
  ChevronRight,
  ArrowUp,
  ArrowDown,
  CornerDownRight,
  type LucideIcon,
} from 'lucide-react'

export const ICONS = {
  // categories
  megaphone: Megaphone,
  laugh: Laugh,
  clapperboard: Clapperboard,
  mic: Mic2,
  shirt: Shirt,
  sparkles: Sparkles,
  utensils: UtensilsCrossed,
  mapPin: MapPin,
  backpack: Backpack,
  coffee: Coffee,
  palette: Palette,
  smartphone: Smartphone,
  // statuses
  sprout: Sprout,
  flame: Flame,
  rocket: Rocket,
  crown: Crown,
  waves: Waves,
  trendingDown: TrendingDown,
  skull: Skull,
  // ui / nav
  home: Home,
  compass: Compass,
  radar: Radar,
  star: Star,
  grid: LayoutGrid,
  search: Search,
  arrowLeft: ArrowLeft,
  check: Check,
  plus: Plus,
  share: Share2,
  idea: Lightbulb,
  trendingUp: TrendingUp,
  clock: Clock,
  hash: Hash,
  network: Network,
  shoppingBag: ShoppingBag,
  chevronRight: ChevronRight,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  related: CornerDownRight,
} satisfies Record<string, LucideIcon>

export type IconName = keyof typeof ICONS
